# 동연님 전처리 파일

In [43]:
import pandas as pd

data = pd.read_csv('../../../files/movie_list.csv')

### null 제거

In [44]:
df = data.dropna(subset=["영화 감독"])

### column 이름 변경

In [45]:
df = df.rename(
    columns={
        "영화제목": "title", 
        "영화 감독": "director", 
        "각본(|| parser)": "screenwriter",
        "왓챠 줄거리": "plot", 
        "왓챠피디아 평점": "rating", 
        "왓챠피디아 평점 수 (명)": "rating_count",
        "주연 (|| parser)": "actors",
        "코멘트 10개 평점 (|| parser)": "comment_ratings",
        "코멘트 10개 멘트 (|| parser)": "comment_texts",
        "장르": "genres",
        "제작 국가(|| parser)": "countries",
        "네이버 누적 관객 수(만명)": "audience",
        "네이버 러닝 타임(분)": "running_time",
        "네이버 19세 여부 (1 or 0)": "adult",
    }
)

### 필요없는 컬럼 삭제 - 관객수
### 관객수 단위 설정 맞추기 필요

In [46]:
df = df.drop(columns=['audience'])

### object column fillna

In [47]:
object_columns = df.select_dtypes(include="object").columns

In [48]:
df[object_columns] = df[object_columns].fillna("")

In [49]:
df.head()

,title,director,screenwriter,plot,rating,rating_count,actors,comment_ratings,comment_texts,genres,countries,running_time,adult
0,월플라워,스티븐 크보스키,스티븐 크보스키,말 못할 트라우마를 가지고 자신만의 세계에 갇혀있던 ‘찰리’는 고등학교 신입생이 돼...,3.8,305000.0,에즈라 밀러||로건 메먼||엠마 왓슨,4.0||5.0||4.0||2.0||4.0||4.0||3.5||4.5||3.5||4.5,그 터널을 무사히 빠져나온 모두에게||사람은 자신의 크기에 맞는 사랑을 한다||샘이...,드라마/로맨스,미국,102.0,0.0
1,기생충,봉준호,봉준호||한진원,“폐 끼치고 싶진 않았어요” 전원백수로 살 길 막막하지만 사이는 좋은 기택(송강호)...,4.3,1265000.0,박소담||송강호||조여정||최우식||이선균||장혜진||이정은,5.0||4.5||5.0||0.5||4.5||5.0||4.0||5.0||5.0||5.0,황금종려상 받은 영화를 자막없이 볼 수 있는 행복 190529||상승과 하강으로 명...,드라마,한국,131.0,0.0
2,메멘토,크리스토퍼 놀란,크리스토퍼 놀란,"아내가 살해당한 후, 10분밖에 기억 못하는 단기기억상실증에 걸린 남자가 사진, 메...",4.1,641000.0,조 판톨리아노||가이 피어스||캐리 앤 모스,5.0||5.0||4.5||5.0||5.0||5.0||5.0||4.0||5.0||4.0,사람은 보고싶은 것만 보고 듣고싶은 것만 듣고 믿고 싶은 것만 믿고 기억하고 싶은 ...,미스터리/스릴러,미국,113.0,0.0
3,노인을 위한 나라는 없다,에단 코엔||조엘 코엔,에단 코엔||조엘 코엔,르웰린 모스(조쉬 브롤린)는 총격전이 벌어진 끔찍한 현장에서 우연히 이백만 달러가 ...,4.0,349000.0,토미 리 존스||하비에르 바르뎀||조쉬 브롤린,5.0||5.0||5.0||5.0||3.5||5.0||5.0||4.5||5.0||5.0,그거 아세요? 이 영화에는 배경음악이 단 일초도 쓰이지 않았다는것||피튀기는 젊은 ...,범죄/드라마/스릴러,미국,122.0,1.0
4,파이트 클럽,데이비드 핀처,짐 유힐,당신이 알고 있는 모든 것은 허구다! 비싼 가구들로 집 안을 채우지만 삶에 강한 공...,4.1,371000.0,브래드 피트||에드워드 노튼||헬레나 본햄 카터,5.0||5.0||5.0||4.5||4.0||5.0||4.0||5.0||3.0||4.5,현대문명의 허상을 조롱하는 통렬한 블랙코미디.||영화 자체가 섹시하다||아주 많은 ...,드라마/액션,미국||독일||이탈리아,139.0,1.0

### || 구분자로 되어 있는 것들 split

In [50]:
for col in ["director", "screenwriter", "actors", "comment_ratings", "genres", "countries", "comment_texts"]:
    df[col] = df[col].apply(lambda x: x.replace('||', '/'))
    df[col] = df[col].apply(lambda x: x.split('/'))

    if col is not 'genres':
        df[col] = df[col].apply(lambda x: ''.join(x).split('||')) # 요것만 바꿈

<>:5: SyntaxWarning: "is not" with a literal. Did you mean "!="?
<>:5: SyntaxWarning: "is not" with a literal. Did you mean "!="?
/var/folders/wd/dcswxbgs1nl3_9qmxwtc6nwr0000gn/T/ipykernel_27285/1307314875.py:5: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if col is not 'genres':

In [51]:
df.head()

,title,director,screenwriter,plot,rating,rating_count,actors,comment_ratings,comment_texts,genres,countries,running_time,adult
0,월플라워,[스티븐 크보스키],[스티븐 크보스키],말 못할 트라우마를 가지고 자신만의 세계에 갇혀있던 ‘찰리’는 고등학교 신입생이 돼...,3.8,305000.0,[에즈라 밀러로건 메먼엠마 왓슨],[4.05.04.02.04.04.03.54.53.54.5],[그 터널을 무사히 빠져나온 모두에게사람은 자신의 크기에 맞는 사랑을 한다샘이라는 ...,"[드라마, 로맨스]",[미국],102.0,0.0
1,기생충,[봉준호],[봉준호한진원],“폐 끼치고 싶진 않았어요” 전원백수로 살 길 막막하지만 사이는 좋은 기택(송강호)...,4.3,1265000.0,[박소담송강호조여정최우식이선균장혜진이정은],[5.04.55.00.54.55.04.05.05.05.0],[황금종려상 받은 영화를 자막없이 볼 수 있는 행복 190529상승과 하강으로 명징...,[드라마],[한국],131.0,0.0
2,메멘토,[크리스토퍼 놀란],[크리스토퍼 놀란],"아내가 살해당한 후, 10분밖에 기억 못하는 단기기억상실증에 걸린 남자가 사진, 메...",4.1,641000.0,[조 판톨리아노가이 피어스캐리 앤 모스],[5.05.04.55.05.05.05.04.05.04.0],[사람은 보고싶은 것만 보고 듣고싶은 것만 듣고 믿고 싶은 것만 믿고 기억하고 싶은...,"[미스터리, 스릴러]",[미국],113.0,0.0
3,노인을 위한 나라는 없다,[에단 코엔조엘 코엔],[에단 코엔조엘 코엔],르웰린 모스(조쉬 브롤린)는 총격전이 벌어진 끔찍한 현장에서 우연히 이백만 달러가 ...,4.0,349000.0,[토미 리 존스하비에르 바르뎀조쉬 브롤린],[5.05.05.05.03.55.05.04.55.05.0],[그거 아세요? 이 영화에는 배경음악이 단 일초도 쓰이지 않았다는것피튀기는 젊은 세...,"[범죄, 드라마, 스릴러]",[미국],122.0,1.0
4,파이트 클럽,[데이비드 핀처],[짐 유힐],당신이 알고 있는 모든 것은 허구다! 비싼 가구들로 집 안을 채우지만 삶에 강한 공...,4.1,371000.0,[브래드 피트에드워드 노튼헬레나 본햄 카터],[5.05.05.04.54.05.04.05.03.04.5],[현대문명의 허상을 조롱하는 통렬한 블랙코미디.영화 자체가 섹시하다아주 많은 경우 ...,"[드라마, 액션]",[미국독일이탈리아],139.0,1.0

In [52]:
df.to_csv("../../../files/preprocessed_movie_sample.csv", index=False)

In [31]:
df

,title,director,screenwriter,plot,rating,rating_count,actors,comment_ratings,comment_texts,genres,countries,running_time,adult
0,월플라워,[스티븐 크보스키],[스티븐 크보스키],말 못할 트라우마를 가지고 자신만의 세계에 갇혀있던 ‘찰리’는 고등학교 신입생이 돼...,3.8,305000.0,"[에즈라 밀러, 로건 메먼, 엠마 왓슨]","[4.0, 5.0, 4.0, 2.0, 4.0, 4.0, 3.5, 4.5, 3.5, ...","[그 터널을 무사히 빠져나온 모두에게, 사람은 자신의 크기에 맞는 사랑을 한다, 샘...","[, 드, 라, 마, , , 로, 맨, 스, ]",[미국],102.0,0.0
1,기생충,[봉준호],"[봉준호, 한진원]",“폐 끼치고 싶진 않았어요” 전원백수로 살 길 막막하지만 사이는 좋은 기택(송강호)...,4.3,1265000.0,"[박소담, 송강호, 조여정, 최우식, 이선균, 장혜진, 이정은]","[5.0, 4.5, 5.0, 0.5, 4.5, 5.0, 4.0, 5.0, 5.0, ...","[황금종려상 받은 영화를 자막없이 볼 수 있는 행복 190529, 상승과 하강으로 ...","[, 드, 라, 마, ]",[한국],131.0,0.0
2,메멘토,[크리스토퍼 놀란],[크리스토퍼 놀란],"아내가 살해당한 후, 10분밖에 기억 못하는 단기기억상실증에 걸린 남자가 사진, 메...",4.1,641000.0,"[조 판톨리아노, 가이 피어스, 캐리 앤 모스]","[5.0, 5.0, 4.5, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, ...",[사람은 보고싶은 것만 보고 듣고싶은 것만 듣고 믿고 싶은 것만 믿고 기억하고 싶은...,"[, 미, 스, 터, 리, , , 스, 릴, 러, ]",[미국],113.0,0.0
3,노인을 위한 나라는 없다,"[에단 코엔, 조엘 코엔]","[에단 코엔, 조엘 코엔]",르웰린 모스(조쉬 브롤린)는 총격전이 벌어진 끔찍한 현장에서 우연히 이백만 달러가 ...,4.0,349000.0,"[토미 리 존스, 하비에르 바르뎀, 조쉬 브롤린]","[5.0, 5.0, 5.0, 5.0, 3.5, 5.0, 5.0, 4.5, 5.0, ...","[그거 아세요? 이 영화에는 배경음악이 단 일초도 쓰이지 않았다는것, 피튀기는 젊은...","[, 범, 죄, , , 드, 라, 마, , , 스, 릴, 러, ]",[미국],122.0,1.0
4,파이트 클럽,[데이비드 핀처],[짐 유힐],당신이 알고 있는 모든 것은 허구다! 비싼 가구들로 집 안을 채우지만 삶에 강한 공...,4.1,371000.0,"[브래드 피트, 에드워드 노튼, 헬레나 본햄 카터]","[5.0, 5.0, 5.0, 4.5, 4.0, 5.0, 4.0, 5.0, 3.0, ...","[현대문명의 허상을 조롱하는 통렬한 블랙코미디., 영화 자체가 섹시하다, 아주 많은...","[, 드, 라, 마, , , 액, 션, ]","[미국, 독일, 이탈리아]",139.0,1.0
5,박화영,[이환],[이환],“니들은 나 없으면 어쩔 뻔 봤냐?” 이름: 박화영 나이: 18 직업: 고등학생 가...,3.3,142000.0,"[김가희, 강민아, 이재균]","[3.0, 3.0, 3.0, 3.0, 4.5, 2.5, 3.5, 3.0, 3.0, ...","[자극적인 장면들을 자꾸 나열한다고 해서 메시지가 더 잘 전달되는 건 아닌데.., ...","[, 드, 라, 마, ]",[한국],112.0,1.0
6,거인,[김태용],[김태용],[2024 문화다양성 주간 / 조해진 작가] 가난하고 비굴한 부모가 있던 집보다 보...,3.7,60000.0,[최우식],"[3.5, 4.0, 3.0, 3.0, 3.5, 3.0, 4.0, 4.0, 3.5, ...","[성장영화가 아닙니다. 일종의 재난영화입니다., 살면서 그런일도 있지. 너보다 불쌍...","[, 드, 라, 마, ]",[한국],108.0,0.0
7,끝까지 간다,[김성훈],[김성훈],"어머니의 장례식 날, 급한 연락을 받고 경찰서로 향하던 형사 ‘고건수’(이선균). ...",3.8,826000.0,"[이선균, 조진웅]","[3.5, 5.0, 5.0, 5.0, 5.0, 3.5, 4.0, 5.0, 4.5, ...","[두 주인공이 처음 직접 대면하게 될 때의 굉장한 박력., 근래 본 영화 중 최고....","[, 범, 죄, , , 액, 션, ]",[한국],111.0,0.0
8,헤드윅,[존 카메론 미첼],[존 카메론 미첼],내게 남은 것은 1인치의 사랑과 열정 세계적인 록스타 ‘토미’의 공연을 쫓아 변두리...,4.0,146000.0,[존 카메론 미첼],"[4.0, 4.5, 5.0, 4.5, 5.0, 5.0, 5.0, 4.0, 5.0, ...","[인정만큼 오만한 단어도 없다. 네가 나의 인정 없이도 존재하듯, 나 역시 너의 인...","[, 음, 악, , , 드, 라, 마, , , 코, 미, 디, ]",[미국],92.0,0.0
9,더 울프 오브 월 스트리트,[마틴 스코세이지],[테런스 윈터],"화려한 언변, 수려한 외모, 명석한 두뇌를 지닌 조단 벨포트(레오나르도 디카프리오)...",3.8,495000.0,"[레오나르도 디카프리오, 조나 힐]","[5.0, 5.0, 4.0, 4.0, 3.0, 4.0, 5.0, 5.0, 4.0, ...","[으으흠~ 으으흠~ 으흐흠흐흐흐흠~ 으흠~, 언제부터인지 디카프리오 영화는 그냥 보...","[, 전, 기, , , 범, 죄, , , 드, 라, 마, ]",[미국],180.0,1.0
10,어바웃타임,[리처드 커티스],[리처드 커티스],"모태솔로 팀(도널 글리슨)은 성인이 된 날, 아버지(빌 나이)로부터 놀랄만한 가문의...",4.3,NaN,"[도널 글리슨 , 레이첼 맥아담스]","[5.0, 4.5, 5.0, 4.0, 4.0, 5.0, 5.0, 5.0, 5.0, ...","[여러분은 남자 주인공이 점점 잘 생겨지는 기적을 만나게 될 겁니다., 무엇보다 아...","[, 판, 타, 지, , , 드, 라, 마, , , 로, 맨, 틱, , 코, 미,...",[영국],123.0,0.0
11,포레스트 검프,[로버트 저메키스],"[로버트 저메키스 , 에릭 로스]","""인생은 초콜릿 상자와 같은 거야. 네가 무엇을 고를지 아무도 모른단다…""\r\n\...",4.5,NaN,[톰 행크스],"[4.0, 5.0, 5.0, 5.0, 4.5, 5.0, 5.0, 3.0, 0.5, ...","[""저애 똑똑해? 아니면 나처럼...""\n에서 눈물이 왈칵 쏟아졌다, 인생을 너무 ...","[, 드, 라, 마, , , 로, 맨, 스, ]",[미국],142.0,0.0
20,인사이드 아웃 2,[켈시 만],[멕 러포브],디즈니·픽사의 대표작 <인사이드 아웃>\n새로운 감정과 함께 돌아오다!\n\n13살...,3.8,92000.0,"[에이미 폴러, 필리스 스미스, 루이스 블랙, 토니 해일, 리자 라피라, 마야 호크...","[3.5, 3.5, 5.0, 4.0, 5.0, 4.5, 4.0, 3.0, 4.5, ...","[그 모든 게 나였다 그 전부가 세월이었다 하나도 남김없이., 그때 잘 다스리지 못...","[, 애, 니, 메, 이, 션, , , 모, 험, , , 코, 미, 디, ]",[미국],96.0,0.0
21,엘리멘탈,[피터 손],"[존 호버그, 캣 리켈, 브렌다 쉬에]",[2024 문화다양성 주간 / 안나 예이츠 교수]\n이 또한 아이에게 문화다양성에 ...,3.8,136000.0,"[로니 델 카르멘, 레아 루이스, 쉴라 옴미, 마무두 아티, 웬디 맥클렌던 커비, ...","[3.5, 3.5, 3.5, 3.5, 5.0, 4.0, 4.5, 3.5, 3.0, ...","[네 빛이 일렁일 때 정말 좋더라, 찐 파도타기 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ, 착하려고 화에...","[, 애, 니, 메, 이, 션, , , 모, 험, , , 판, 타, 지, , , S...",[미국],109.0,0.0
22,서울의 봄,[김성수],[정현수],"1979년 12월 12일, 수도 서울 군사반란 발생\r\n그날, 대한민국의 운명이 ...",3.9,130000.0,"[황정민, 정우성]","[5.0, 3.5, 4.0, 3.5, 4.5, 3.5, 4.0, 4.5, 4.0, ...","[하아 대머리 죽었지만 다시 죽이고픔, 야만과 무능의 그 겨울밤에 대한 분노가 시종...","[, 드, 라, 마, ]",[한국],141.0,0.0
23,컨택트,[드니 빌뇌브],[에릭 하이저러],외계에서 온 비행물체들이 거대한 위용을 자랑하며 지구에 도착하지만 왜 그들이 지구에...,4.0,468000.0,"[에이미 아담스, 제레미 레너]","[4.5, 5.0, 3.5, 4.0, 4.5, 3.5, 4.0, 4.5, 4.0, ...",[실패를 두려워하지 말 것.\r\n당신 인생의 찬란한 순간들을 사랑할 것.\r\n\...,"[, 미, 스, 터, 리, , , S, F, , , 스, 릴, 러, , , 드, 라...",[미국],116.0,0.0
24,매드맥스: 분노의 도로,[조지 밀러],"[닉 라소리스, 브렌단 맥카시, 조지 밀러]",“세상이 멸망하면서 누가 미친 건지 알 수 없어졌다. 나인지 이 세상인지..”\n\...,4.2,788000.0,"[샤를리즈 테론, 톰 하디, 니콜라스 홀트]","[4.0, 4.5, 4.5, 5.0, 5.0, 4.5, 4.0, 4.5, 4.0, ...","[제목이 매드맥슨데 맥스가 제일 제정신, 같은 후기 다른 느낌\r\n위플래쉬: 이 ...","[, 액, 션, , , 모, 험, , , S, F, , , 스, 릴, 러, ]","[미국, 호주]",120.0,0.0
25,향수 - 어느 살인자의 이야기,[톰 티크베어],"[톰 티크베어, 베른트 아이힝거, 앤드류 버킨]","18세기 프랑스, 악취나는 생선 시장에서 태어나자마자 고아가 된 천재적인 후각의 소...",3.7,597000.0,"[장 바티스트 그루누이, 주세페 발디니]","[4.5, 5.0, 2.5, 0.5, 3.5, 4.0, 4.0, 0.5, 4.5, ...",[아이러니하게도 지금의 우리도 주인공과 다를바없지않은가\r\n\r\n진정한 자신의 ...,"[, 범, 죄, , , 드, 라, 마, , , 스, 릴, 러, ]","[독일, 프랑스, 스페인, 미국]",146.0,0.0
26,탑건: 매버릭,[조셉 코신스키],"[에런 크루거, 에릭 워런 싱어, 크리스토퍼 매쿼리]","한순간의 실수도 용납되지 않는 하늘 위,\r\n가장 압도적인 비행이 시작된다!\r\...",4.1,148000.0,[톰 크루즈],"[4.0, 4.5, 4.5, 5.0, 4.5, 4.0, 5.0, 4.0, 5.0, ...","[기계가 인간을 대체해가는 시대에 아직은 어림없다고 외치는 사자후., 관람 시작 전...","[, 액, 션, , , 드, 라, 마, ]",[미국],130.0,0.0
27,세 얼간이,[라지쿠마르 히라니],"[라지쿠마르 히라니, 아비잣 조쉬]","천재들만 간다는 일류 명문대 ICE, 성적과 취업만을 강요하는 학교를 발칵 뒤집어 ...",4.1,1451000.0,"[아미르 칸, 마드하반, 셔먼 조쉬, 카리나 카푸르, 보만 이라니, 오미 베이디아]","[5.0, 5.0, 3.0, 4.0, 5.0, 3.5, 5.0, 4.0, 5.0, ...",[뻔해서 싫다고? 진리는 원래 평범한 법. 뻔한 내용을 지루하지 않게 표현하는 것도...,"[, 뮤, 지, 컬, , , 코, 미, 디, , , 드, 라, 마, ]",[인도],141.0,0.0
28,리미트리스,[닐 버거],[레슬리 딕슨],마감 날짜가 다가오지만 한 글자도 쓰지 못한 무능력한 작가 '에디 모라'(브래들리 ...,3.9,425000.0,"[브래들리 쿠퍼, 로버트 드 니로, 애비 코니쉬]","[3.0, 3.5, 4.0, 4.0, 3.0, 4.5, 3.0, 4.0, 3.5, ...",[우리나라 평이 왜이렇게 좋은지는 모르겠으나 완성도가 떨어진다고 생각한다. 사건 마...,"[, S, F, , , 스, 릴, 러, , , 액, 션, , , 미, 스, 터, 리, ]",[미국],105.0,0.0
29,킹스맨: 시크릿 에이전트,[매튜 본],"[제인 골드먼, 매슈 본]","세상에서 가장 위험한 면접이 시작된다!\r\n\r\n높은 IQ, 주니어 체조대회 2...",4.1,896000.0,"[태런 애저튼, 콜린 퍼스]","[4.0, 3.5, 4.0, 4.5, 5.0, 5.0, 4.5, 4.5, 5.0, ...",[콜린 퍼스.. 왜 액션을 안 찍나 했더니 나같은 빠순이 감당 못할까 봐 배려한 거...,"[, 액, 션, , , 범, 죄, , , 코, 미, 디, , , 모, 험, , , ...","[영국, 미국]",128.0,1.0
30,데드풀과 울버린,[숀 레비],"[라이언 레이놀즈, 렛 리스, 폴 워닉, 제브 웰스, 숀 레비]","히어로 생활에서 은퇴한 후, 평범한 중고차 딜러로 살아가던 ‘데드풀’이 예상치 못한...",3.3,35000.0,"[라이언 레이놀즈, 휴 잭맨]","[3.0, 5.0, 4.0, 2.0, 2.0, 4.0, 3.0, 4.0, 3.5, ...","[인수합병에 대한 재치있는 비즈니스영화, 경혈을 찾아 침을 놓아가며 갈증을 잠시 해...","[, 액, 션, , , 코, 미, 디, , , S, F, ]",[미국],128.0,1.0
31,범죄도시4,[허명행],[오상호],"신종 마약 사건 3년 뒤, 괴물형사 ‘마석도’(마동석)와 서울 광수대는 배달앱을 이...",2.9,59000.0,[마동석],"[2.0, 2.5, 3.5, 4.5, 2.5, 3.5, 2.0, 3.0, 2.5, ...","[갑티슈 속 상권 독점, 영화관의 스크린 독점., 익숙함에서 진부함으로 넘어가는 고...","[, 범, 죄, ]",[대한민국],105.0,0.0
32,범죄도시3,[이상용],"[김민성, 차우진]","대체불가 괴물형사 마석도, 서울 광수대로 발탁! 베트남 납치 살해범 검거 후 7년 ...",2.9,88000.0,"[마동석, 이준혁]","[3.5, 3.0, 4.5, 3.0, 3.0, 2.5, 1.0, 2.5, 3.0, ...","[고착화의 불안감이 엄습해오나 아직까진 관객에게 유효타가 먹혀든 후속작., 기회가 ...","[, 범, 죄, ]",[대한민국],105.0,0.0
33,더 퍼스트 슬램덩크,[이노우에 다케히코],[이노우에 다케히코],"전국 제패를 꿈꾸는 북산고 농구부 5인방의 꿈과 열정, 멈추지 않는 도전을 그린 영화",4.1,100000.0,[나카무라 슈고],"[5.0, 3.5, 5.0, 4.0, 5.0, 4.5, 4.5, 5.0, 4.0, ...","[첫사랑한테 4.5를 주는 바보는 없어, 숨죽이게 하고 환호하게 하며 뜨거운 마음으...","[, 애, 니, 메, 이, 션, , , 스, 포, 츠, ]",[일본],124.0,0.0
34,탈주,[이종필],"[권성휘, 김우근]",“내 앞 길 내가 정했습니다” 휴전선 인근 북한 최전방 군부대. 10년 만기 제대를...,3.1,27000.0,"[이제훈, 구교환]","[1.5, 2.5, 4.0, 2.5, 1.5, 1.5, 0.5, 4.0, 3.0, ...",[- 내가 기대한 것: 북한군 버전 D.P.\n- 실제로 본 것: 자이언티와 함께하...,"[, 액, 션, , , 스, 릴, 러, ]",[대한민국],94.0,0.0
35,듄: 파트2,[드니 빌뇌브],"[드니 빌뇌브, 존 스페이츠]",황제의 모략으로 멸문한 가문의 유일한 후계자 폴.(티모시 샬라메) 어머니 레이디 제...,4.1,70000.0,[티모시 샬라메],"[4.0, 4.0, 5.0, 3.0, 4.5, 2.0, 4.5, 5.0, 3.5, ...","[젠다이아 리산 미가입, 한 방울도 헛되이 흘리지 않는 영화의 지독한 세공력과 우아...","[, 액, 션, , , 모, 험, , , 드, 라, 마, , , S, F, ]",[미국캐나다],166.0,0.0
36,파일럿,[김한결],"[조유진, 김한결, 한준희]",하루 아침에 인생 추락한 스타 파일럿 제 2의 인생 이륙 준비 중! 최고의 비행 실...,2.8,21000.0,[조정석],"[2.0, 3.0, 2.5, 1.5, 3.0, 2.0, 2.5, 1.0, 2.5, ...",[으레 이런 류의 영화 문법은 주인공이 변화를 겪고 이전과 다른 사람이 되어야 한다...,"[, 코, 미, 디, ]",[대한민국],111.0,0.0
38,파묘,[장재현],[장재현],"미국 LA, 거액의 의뢰를 받은 무당 ‘화림’(김고은)과 ‘봉길’(이도현)은 기이한...",3.5,161000.0,"[최민식, 김고은, 유해진, 이도현]","[3.5, 3.5, 4.0, 4.5, 2.5, 2.0, 3.5, 2.0, 3.5, ...","[왜놈새끼 죽어서도 지랄이네…, 돼지띠 청년들 이 영화 보시고 일자리 정보 얻어가세...","[, 미, 스, 터, 리, , , 스, 릴, 러, ]",[대한민국],134.0,0.0
39,웡카,[폴 킹],"[사이먼 파너비, 폴 킹]",세상에서 가장 달콤한 여정 좋은 일은 모두 꿈에서부터 시작된다! 마법사이자 초콜릿 ...,3.3,60000.0,[티모시 샬라메],"[3.0, 3.0, 3.0, 3.5, 4.0, 4.0, 2.0, 3.0, 2.0, ...",[3.0\ncontent\n섭취하기 쉽게 잘라놓은 낭만과 향수 속에서 티모시 샤르르...,"[, 판, 타, 지, , , 모, 험, , , 코, 미, 디, , , 뮤, 지, 컬...",[미국],116.0,0.0
40,아가일,[매튜 본],[제이슨 푸치스],"소설 내용이 현실 속 악당 스파이 조직의 활동을 그대로 묘사하자, 소심한 첩보 소설...",2.9,8028.0,"[헨리 카빌, 브라이스 달라스 하워드, 샘 록웰]","[3.0, 3.0, 4.5, 3.5, 3.0, 2.0, 3.5, 2.5, 3.5, ...","[요란하게 피워올리고 리드미컬하게 누비는 사이키델릭 액션의 재미., 반전들이 다소 ...","[, ]",[액션스릴러],139.0,0.0
41,레이니 데이 인 뉴욕,[우디 앨런],[우디 앨런],상상해 봐요 막 떨어지기 시작한 빗방울 센트럴 파크 델라코트 시계 아래 누군가 당신...,3.3,37000.0,"[티모시 샬라메, 엘 패닝, ]","[3.0, 4.0, 4.5, 0.5, 3.5, 3.5, 3.5, 4.0, 3.0, ...",[홍상수처럼 구구절절\n약팔고 있네.. 라는 생각이 들면서도\n'어디서' '어떤 ...,"[, 코, 미, 디, , , 로, 맨, 스, ]",[미국],92.0,0.0
42,혹성탈출: 새로운 시대,[웨스 볼],"[조시 프리드먼, 릭 자파, 아만다 실버, 패트릭 아이슨]","인류의 시대는 끝났고, 세상의 주인이 바뀌었다! 진화한 유인원과 퇴화된 인간들이 살...",3.2,14000.0,[오웬 티그],"[3.5, 3.5, 3.5, 2.0, 3.0, 2.5, 4.0, 3.5, 3.5, ...","[무엇을 어떻게 계승할 것인지에 대한 숙고가 담긴 품격 높은 블록버스터의 재래., ...","[, 액, 션, , , S, F, ]",[미국],145.0,0.0
43,콰이어트 플레이스: 첫째 날,[마이클 사노스키],"[마이클 사노스키, 존 크래신스키, 브라이언 우즈]","쉿, 살고 싶다면 절대 소리내지 말 것! 평균 소음 90 데시벨을 자랑하는 미국 최...",2.8,11000.0,"[루피타 뇽오, 자이먼 운수, 알렉스 울프, 조셉 퀸]",[],"[고양이가 울지도 않고 씩씩하네요., 팝콘무비 주제에 팝콘 씹는 소리조차 용납하지 ...","[, 드, 라, 마, , , 공, 포, , , S, F, , , 스, 릴, 러, ]",[미국],99.0,0.0
44,타짜,[최동훈],"[허영만, 최동훈]",가구공장에서 일하며 남루한 삶을 사는 고니는 대학보다 가난을 벗어나게 해줄 돈이 우...,4.2,1196000.0,"[조승우, 백윤식, 유해진, 김혜수]","[5.0, 4.5, 5.0, 5.0, 4.5, 5.0, 4.5, 5.0, 5.0, ...","[이제 소리끄고도 볼 수 있음, 2시간 19분이 1시간 19분처럼 지나간다, 그강의...","[, 드, 라, 마, ]",[대한민국],139.0,1.0
45,범죄의 재구성,[최동훈],[최동훈],"사기 전과로 출소한지 한 달, 최창혁(박신양)은 흥미로운 사기 사건을 계획한다. 그...",3.8,308000.0,"[염정아, 박신양, 이문식, 백윤식]","[4.0, 4.0, 4.0, 4.0, 3.5, 2.0, 3.0, 4.0, 4.0, ...","[Coooooooool !, ""결혼할꺼냐? 결혼해라 이 여자가 널 살렸다"", 귀에 ...","[, 범, 죄, |, |, 스, 릴, 러, |, |, 코, 미, 디, ]",[대한민국],116.0,1.0
46,케빈에 대하여,[린 램지],"[린 램지, 로리키니어]",자유로운 삶을 즐기던 여행가 에바에게 아들 케빈이 생기면서 그녀의 삶은 180도 달...,3.9,320000.0,"[제스터 뉴엘, 틸다 스윈튼, 존 C.라일리, 에즈라 밀러]","[5.0, 4.5, 4.5, 5.0, 4.0, 5.0, 4.0, 5.0, 4.5, ...",[엄마를 사랑하지만 그렇지 않은 척한 아들과 아들을 사랑하지 않지만 사랑하는 척한 ...,"[, 드, 라, 마, |, |, 미, 스, 터, 리, |, |, 스, 릴, 러, ]","[미국, 영국]",112.0,1.0
47,아마데우스,[밀로스 포먼],[피터 셰퍼],"1823년 눈보라치는 밤, 한 노인이 자살을 시도하다 실패하여 수용소에 수감된다. ...",4.0,199000.0,"[엘리자베스 베리지, F.머레이 에이브라함, 로이 도트라이스, 톰 헐스]","[4.5, 5.0, 4.5, 5.0, 4.5, 4.5, 4.5, 5.0, 5.0, ...","[흥미로운 각본, 우아한 연출, 좋은 연기를 모두 갖춘 음악영화의 품격., 재능을 ...","[, 전, 기, |, |, 드, 라, 미, |, |, 음, 악, ]","[미국, 프랑스]",180.0,0.0
48,반지의제왕 : 반지 원정대,[피터 잭슨],"[피터 잭슨, 프랜 월시, 필리파 보옌스]",마지막 반지를 차지하는 자\n모든 힘을 지배하게 될 것이다!\n\n모든 힘을 지배할...,4.1,708000.0,"[비고 모텐슨, 일라이저 우드, 숀 애스틴, 이안 맥켈런, 리브 타일러, 케이트 블란쳇]","[5.0, 4.0, 4.0, 3.5, 0.5, 4.0, 5.0, 3.5, 5.0, ...","[전설의시작, 1편의 짧은 등장에도 시리즈가 끝날 때까지 자신의 빈자리를 남겼던 보...","[, 판, 타, 지, |, |, 드, 라, 마, |, |, 액, 션, |, |, 모...","[뉴질랜드, 미국]",228.0,0.0
49,글레디에이터,[리들리 스콧],"[데이비드 프란조니, 존 로건, 윌리엄 니콜슨]",죽을 날이 머지않은 황제 마르쿠스 아우렐리우스는 막시무스를 총애하여 아들이 아닌 그...,4.1,459000.0,"[코니 닐슨, 러셀 크로우, 올리버 리드, 호아킨 피닉스]","[5.0, 4.0, 4.0, 4.0, 4.5, 3.5, 3.5, 4.5, 4.5, ...",[폭력과 살육의 쾌감에 젖어 민주주의란 말이 무색할정도로 수동적이고 인간성을상실한 ...,"[, 액, 션, |, |, 드, 라, 마, |, |, 모, 험, ]","[영국, 미국]",154.0,0.0
50,"광해, 왕이 된 남자",[추창민],"[황조윤, 안소정]",왕위를 둘러싼 권력 다툼과 당쟁으로 혼란이 극에 달한 광해군 8년. 자신의 목숨을 ...,4.0,1857000.0,"[이병헌, 류승룡, 한효주]","[3.5, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 3.5, ...","[대중영화의 모범적 연기와 화술. 반듯하고 번듯하다., 도부장-너희들에게는 가짜 왕...","[, ]",[],NaN,NaN
51,바스터즈: 거친 녀석들,[쿠엔틴 타란티노],[쿠엔틴 타란티노],"2차 세계 대전, 나치의 잔인하고 폭력적인 행태에 분개한 미군 알도 레인 중위(브래...",4.1,307000.0,"[크리스토프 발츠, 브래드 피트, 일라이 토스, 멜라니 로랑, 마이클 패스벤더, 다...","[4.5, 5.0, 4.5, 5.0, 5.0, 4.0, 4.0, 4.5, 5.0, ...","[우리나라에서도 일본 전범들 족치는 그런 영화가 나오면 좋을텐데.., (거의) 모든...","[, 모, 험, |, |, 드, 라, 마, |, |, 전, 쟁, ]","[미국, 독일]",152.0,1.0
52,공작,[윤종빈],"[권성휘, 윤종빈]","1993년, 북한 핵 개발을 둘러싸고 한반도의 위기가 고조된다. 정보사 소령 출신으...",3.7,410000.0,"[조진웅, 황정민, 주지훈, 이성민]","[3.5, 4.0, 4.0, 4.0, 3.0, 3.5, 3.5, 3.5, 4.5, ...",[뻔한 액션을 배제한 채 말의 전쟁을 생생히 살려낸 한국 첩보영화의 뚜렷한 성취(와...,"[, 드, 라, 마, ]",[대한민국],137.0,0.0
53,크레이지 스투피브 러브,"[존 레쿼, 글렌 피카라]",[댄 포겔만],"좋은 직장, 좋은 집, 그리고 멋진 아이들까지 모든 것이 완벽하게 이뤄져가는 삶을 ...",3.5,44000.0,"[엠마 스톤, 라이언 고슬링, 스티브 카렐]","[4.0, 3.5, 3.0, 4.0, 5.0, 4.0, 3.0, 3.5, 4.0, ...","[아, 유쾌하다 유쾌해. 아무 기대도 없이 봤는데 이렇게 재밌을 줄이야. 진부하지만...","[, 로, 맨, 틱, , 코, 미, 디, |, |, 드, 라, 마, |, |, 코...",[미국],118.0,0.0